<?php
/**
 * contact.php — Contact form API handler
 * Accepts POST only. Returns JSON. Used by script.js via fetch().
 */
declare(strict_types=1);
header('Content-Type: application/json; charset=UTF-8');

// Only allow POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed.']);
    exit;
}

require_once __DIR__ . '/config/db.php';

// ── Session & Rate Limiting ─────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$now    = time();
$window = 300; // 5 minutes
$limit  = 3;   // max 3 submissions per window

// Purge old attempts
$_SESSION['contact_attempts'] = array_values(
    array_filter($_SESSION['contact_attempts'] ?? [], fn($t) => ($now - $t) < $window)
);

if (count($_SESSION['contact_attempts']) >= $limit) {
    http_response_code(429);
    echo json_encode(['success' => false, 'message' => 'Too many submissions. Please wait a few minutes and try again.']);
    exit;
}

// ── CSRF Verification ───────────────────────────────────────
// (Token generated by script.js on page load from a meta tag — see index.php)
// For this simple portfolio, we rely on rate limiting + field validation.
// To add CSRF: generate token in index.php session, verify here.

// ── Sanitize & Validate Inputs ──────────────────────────────
$name    = mb_substr(trim(strip_tags($_POST['name']    ?? '')), 0, 100);
$email   = mb_substr(trim($_POST['email']              ?? ''), 0, 254);
$subject = mb_substr(trim(strip_tags($_POST['subject'] ?? '')), 0, 200);
$message = mb_substr(trim(strip_tags($_POST['message'] ?? '')), 0, 5000);

$errors = [];

if (mb_strlen($name) < 2)    $errors[] = 'Name must be at least 2 characters.';
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) $errors[] = 'Please enter a valid email address.';
if (mb_strlen($subject) < 3) $errors[] = 'Subject must be at least 3 characters.';
if (mb_strlen($message) < 10) $errors[] = 'Message must be at least 10 characters.';

// Basic spam honeypot (if form has a hidden field, bot filled it)
if (!empty($_POST['website'])) {
    // Silently discard — looks like a success to the bot
    echo json_encode(['success' => true]);
    exit;
}

if (!empty($errors)) {
    http_response_code(422);
    echo json_encode(['success' => false, 'message' => implode(' ', $errors)]);
    exit;
}

$email = strtolower($email);
$ip    = $_SERVER['REMOTE_ADDR'] ?? 'unknown';

// ── Prepared Statement Insert ───────────────────────────────
$stmt = $conn->prepare(
    'INSERT INTO contact_messages (name, email, subject, message, ip_address)
     VALUES (?, ?, ?, ?, ?)'
);
$stmt->bind_param('sssss', $name, $email, $subject, $message, $ip);

if ($stmt->execute()) {
    $_SESSION['contact_attempts'][] = $now;
    $stmt->close();
    echo json_encode(['success' => true]);
} else {
    $stmt->close();
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Failed to send your message. Please try again later.']);
}
